### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by Aarnnity** [WissamAKRETCHE/DDPG-Keras-TORCS#1]
Hi, I am following your request. Installed pytorch=0.4.1. But an error occurred. Can you help solve it?
My environment:
python=3.6
cuda=10.0
cudnn=0.7.0

error:
Traceback (most recent call last):
  File "/home/tk/PycharmProjects/TD3New/main.py", line 96, in <module>
    a_t_original = actor(torch.tensor(s_t.reshape(1, s_t.shape[0]), device=device).float())
  File "/home/tk/anaconda3/envs/TD3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tk/PycharmProjects/TD3New/ActorNetwork.py", line 27, in forward
    x = F.relu(self.fc1(x))
  File "/home/tk/anaconda3/envs/TD3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tk/anaconda3/envs/TD3/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/tk/anaconda3/envs/TD3/lib/python3.6/site-packages/torch/nn/functional.py", line 1024, in linear
    return torch.addmm(bias, input, weight.t())
RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1533672544752/work/aten/src/THC/THCBlas.cu:249

**Comment by WissamAKRETCHE** [comment]
Hello !
Have you tried to update your torch version from 0.4 to 1.2 ? It's quite similar to the issue [#25165](https://github.com/pytorch/pytorch/issues/25165) and someone fixed it by updating Pytorch version. Please let me know if it worked for you :)
Have a good day,
Wissam

**Comment by Aarnnity** [comment]
> Hello !
> Have you tried to update your torch version from 0.4 to 1.2 ? It's quite similar to the issue [#25165](https://github.com/pytorch/pytorch/issues/25165) and someone fixed it by updating Pytorch version. Please let me know if it worked for you :)
> Have a good day,
> Wissam

Okay, I will try to do this later, and I will give you the answer after I get the result. It can run now because I changed this line of code.
device = torch.device("cuda" if torch.cuda.is_available() else "cpu"). 
thank you for your reply.

**Comment by Ravenclaw-Hcmut** [comment]
> > Hello !
> > Have you tried to update your torch version from 0.4 to 1.2 ? It's quite similar to the issue [#25165](https://github.com/pytorch/pytorch/issues/25165) and someone fixed it by updating Pytorch version. Please let me know if it worked for you :)
> > Have a good day,
> > Wissam
> 
> Okay, I will try to do this later, and I will give you the answer after I get the result. It can run now because I changed this line of code. device = torch.device("cuda" if torch.cuda.is_available() else "cpu"). thank you for your reply.

 I had the same problem while using colab pro. Did you handle it after updating the torch version?
